
package Formularios;
import Clases.*;
import Clases.Clientes;
import Util.Controlador;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Osri
 */
public class ClienteFactura extends javax.swing.JFrame {

    Controlador obj=new Controlador();
    public ClienteFactura() {
        initComponents();
        muestra();
    }
    
    void muestra(){
        DefaultTableModel dt=(DefaultTableModel)CliTab.getModel();
        dt.setRowCount(0);
        String prob ="";
        
        for(Clientes x: obj.listadoCli()){
            if(x.getEstado().equals("1")){
                if(x.getDni() == null){
                prob = x.getRuc();
                }else{prob = x.getDni();}
            Object v[]={x.getCodC(), x.getNom(), prob,
                x.getTelefono(), x.getCod_dis(), x.getDirec(), x.getEstado()};
            dt.addRow(v);}}
        
        
    }
    void muestra2(String cli){
        DefaultTableModel dt=(DefaultTableModel)TabFactura.getModel();
        dt.setRowCount(0);
        
         for(Factura x: obj.listadoR(cli)){
            if(x.getEstado() == 1){
                
            Object v[]={x.getNumRecibo(), x.getFecha(), x.getIgv(),
                x.getCodigoEmp(),x.getEstado(), x.getCodCli(),x.getTp(),x.getGremi()};
            dt.addRow(v);}}
    }
    void muestra3(String fac){
        DefaultTableModel dt=(DefaultTableModel)TabDetalle.getModel();
        dt.setRowCount(0);
         for(DetalleR x: obj.listadoD(fac)){
            if(x.getEst() == 1){
            Object v[]={x.getCodp(), x.getCodMarca(), x.getCant(),
                x.getPrecio(), x.PrecioV()};
            dt.addRow(v);}}
    }
    void LimpiarTabla() {
        DefaultTableModel dt=(DefaultTableModel)TabDetalle.getModel();
        while(dt.getRowCount() > 0)
            {
            dt.removeRow(0);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CliTab = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabFactura = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabDetalle = new javax.swing.JTable();

        setTitle("Módulo: Consulta");
        setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setText("Cliente");

        CliTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre/Razon", "DNI/RUC", "Telefono", "Distrito", "Direccion", "Estado"
            }
        ));
        CliTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CliTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CliTab);

        jLabel2.setText("Factura");

        TabFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero Factura", "Fecha", "IGV", "Codigo vendedor", "Estado", "Codigo cliente", "Tipo", "Guia Remision"
            }
        ));
        TabFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabFacturaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabFactura);

        jLabel3.setText("Detalle Factura");

        TabDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo Producto", "Codigo marca", "Cantidad", "Precio unidad", "Precio Venta"
            }
        ));
        jScrollPane3.setViewportView(TabDetalle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 709, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CliTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CliTabMouseClicked
        int f=CliTab.getSelectedRow();
        String cod=CliTab.getValueAt(f, 0).toString();
        LimpiarTabla();
        muestra2(cod);
    }//GEN-LAST:event_CliTabMouseClicked

    private void TabFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabFacturaMouseClicked
        int f=TabFactura.getSelectedRow();
        String cod= TabFactura.getValueAt(f, 0).toString();
        LimpiarTabla();
        muestra3(cod);
    }//GEN-LAST:event_TabFacturaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CliTab;
    private javax.swing.JTable TabDetalle;
    private javax.swing.JTable TabFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
